POST http://localhost:3001/api/register
Content-Type: application/json

{
        "name": "joshie",
        "email": "joshua.archer@students.mq.edu.au",
        "password": "josha",
        "address": "cool lane",
        "about": "dsd",
}