POST http://localhost:3001/api/register
Content-Type: application/json

{
   "name": "Billy Bob",
   "email": "billy.b@email.com",
   "address": "Cool Man Lane",
   "about" : "My name is Billy",
   "password": "billyb",
   "coins": 1000000
}